
server:
   port: 9911
#logging.level.root=debug
spring:
   level:
      root: debug
   profiles:
      active: native

# Use the below Config if you are having your yml in different folder.       
#    cloud:
#       config:
#          server:
#             native:
#                searchLocations: file://${user.home}/logs/

#spring.application.name=test
